FROM golang:1.9

WORKDIR /go/src/cloud-microservice-go
COPY . .
WORKDIR /eventservice
RUN CGO_ENABLED=0 GOOS=linux build -a installsuffix cgo -o eventservice

FROM scratch

COPY --from=0 /go/src/cloud-microservice-go/eventservice /eventservice
ENV LISTEN URL=0.0.0.0:8181
EXPOSE 8181
CMD [ "/eventservice" ]

