FROM golang:1.9

WORKDIR /go/src/cloud-microservice-go
COPY . .
WORKDIR /bookingservice
RUN CGO_ENABLED=0 GOOS=linux build -a installsuffix cgo -o bookingservice

FROM scratch

COPY --from=0 /go/src/cloud-microservice-go/bookingservice /bookingservice
ENV LISTEN URL=0.0.0.0:8181
EXPOSE 8181
CMD [ "/bookingservice" ]

